export const GET_SORTBY = 'GET_SORTBY';
export const GET_SEARCHBY = 'GET_SEARCHBY';
export const GET_HOTMOVIE = 'GET_HOTMOVIE';
export const GET_MOVIE_TITLE = 'GET_MOVIE_TITLE';
export const GET_SAMEGENRE = 'GET_SAMEGENRE';
export const GET_PAGE_PARAMS = 'GET_PAGE_PARAMS';
export const GET_PAGE_PARAMS_DEFAULT = 'GET_PAGE_PARAMS_DEFAULT';

export const GET_SORTBY_RATING = 'GET_SORTBY_RATING';
export const GET_SORTBY_RELEASE = 'GET_SORTBY_RELEASE';

export const REQUEST_MOVIE = 'REQUEST_MOVIE';
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE';
export const FAILURE_MOVIE_REQUEST = 'FAILURE_MOVIE_REQUEST';

export const REQUEST_MOVIE_BY_ID = 'REQUEST_MOVIE_BY_ID';
export const RECEIVE_MOVIE_BY_ID = 'RECEIVE_MOVIE_BY_ID';
export const FAILURE_MOVIE_REQUEST_BY_ID = 'FAILURE_MOVIE_REQUEST_BY_ID';

export const ADD_TO_BUCKET = 'ADD_TO_BUCKET';
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export const DELETE_ORDER = 'DELETE_ORDER';
export const CHANGE_ORDER = 'CHANGE_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const FAILURE_ORDERS_REQUEST = 'FAILURE_ORDERS_REQUEST';
